"use client";

import { useEffect, useState } from "react";
import Image from "next/image";

export default function TestOutputPage() {
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Check if test-output.png exists
    const checkImage = async () => {
      try {
        // Try to load the image
        const img = new window.Image();
        img.onload = () => {
          setImageUrl("/test-output.png");
          setLoading(false);
        };
        img.onerror = () => {
          setError("Test output image not found. Please run test.js first.");
          setLoading(false);
        };
        // Add timestamp to bypass cache
        img.src = `/test-output.png?t=${Date.now()}`;
      } catch (err) {
        setError("Error loading image");
        setLoading(false);
      }
    };

    checkImage();
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gray-900 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading test output...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center max-w-md mx-auto p-8">
          <div className="bg-red-50 border border-red-200 rounded-lg p-6">
            <h1 className="text-2xl font-semibold text-red-800 mb-2">
              Image Not Found
            </h1>
            <p className="text-red-600 mb-4">{error}</p>
            <p className="text-sm text-gray-600">
              Run <code className="bg-gray-100 px-2 py-1 rounded">node test.js</code> to
              generate the test output image.
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-6">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            Test Output - Framed Watercolor Painting
          </h1>
          <p className="text-gray-600">
            Generated using Gemini 3 Pro Image Preview
          </p>
        </div>

        <div className="bg-white rounded-lg shadow-lg p-6">
          <div className="flex justify-center items-center">
            <div className="relative max-w-full">
              {imageUrl && (
                <img
                  src={`${imageUrl}?t=${Date.now()}`}
                  alt="Test output - Framed watercolor painting"
                  className="max-w-full h-auto rounded-lg shadow-md"
                  style={{ maxHeight: "90vh" }}
                />
              )}
            </div>
          </div>

          <div className="mt-6 flex gap-4 justify-center">
            <button
              onClick={() => {
                window.location.reload();
              }}
              className="px-4 py-2 bg-gray-900 text-white rounded-lg hover:bg-gray-800 transition-colors"
            >
              Refresh Image
            </button>
            {imageUrl && (
              <a
                href={`${imageUrl}?t=${Date.now()}`}
                download="test-output.png"
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
              >
                Download Image
              </a>
            )}
          </div>
        </div>

        <div className="mt-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
          <p className="text-sm text-blue-800">
            <strong>Note:</strong> This image is generated by running{" "}
            <code className="bg-blue-100 px-2 py-1 rounded">node test.js</code>.
            The image is saved as <code className="bg-blue-100 px-2 py-1 rounded">test-output.png</code> in
            the project root.
          </p>
        </div>
      </div>
    </div>
  );
}

